name: Build with debian 11

on:
  push:
    branches: 
      - devops

env:
  DOCKERFILE_NAME: Dockerfile.debian11

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Docker image tag
      run: |
        echo "DOCKER_IMAGE_TAG=pyroscope-`date +'%Y%m%d'`-${GITHUB_SHA::8}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
    - name: Docker build and push
      run: |
        docker build -f ${DOCKERFILE_NAME} -t ${DOCKER_IMAGE_TAG} .
    # - name: Wechatwork robot notify
    #   if: success()
    #   uses: blunt1973/wechatwork-action@master
    #   with:
    #     url: ${{ secrets.WECHATWORK_DEVOPS_WEBHOOK}}
    #     type: markdown
    #     content: |
    #       ${DOCKER_IMAGE_NAME} build success!